import type { Section } from '@/types';

/**
 * 11개 섹션 — 오프라인 행사장 동선과 동일한 배치.
 * hallPosition 은 조감도 좌표(미터 단위 가정). 코드 수정 없이 배치 변경이 가능하도록
 * 반드시 이 데이터(=Firestore sections)만 보고 3D 씬을 그린다. (GUIDE 5장)
 */
export const SECTIONS: Section[] = [
  {
    id: 'welcome',
    order: 1,
    slug: 'welcome',
    title: '웰컴존',
    subtitle: '대표님 인사 · 응원 메시지 · 오늘의 동선',
    type: 'video',
    hallPosition: { x: -19, z: 13, w: 11, d: 9 },
    requiredProductIds: ['pw-ceo', 'pw-celeb'],
    minDwellSec: 20,
    estMinutes: 5,
    mdIds: ['md-hq'],
    isOpen: true,
    color: '#1f6feb',
  },
  {
    id: 'media',
    order: 2,
    slug: 'media',
    title: '미디어 시청',
    subtitle: '2027 상품전략 메인 영상',
    type: 'video',
    hallPosition: { x: -6.5, z: 13, w: 11, d: 9 },
    requiredProductIds: ['pm-main'],
    minDwellSec: 20,
    estMinutes: 7,
    mdIds: ['md-hq'],
    isOpen: true,
    color: '#2b7fff',
  },
  {
    id: 'standard-store',
    order: 3,
    slug: 'standard-store',
    title: '표준매장 둘러보기',
    subtitle: '2027 표준 레이아웃 · 진열 원칙',
    type: 'shelf3d',
    modelPath: '/models/standard-store.glb',
    hallPosition: { x: 9, z: 12.5, w: 17, d: 10 },
    requiredProductIds: ['ps-layout', 'ps-gondola', 'ps-walkin', 'ps-endcap'],
    minDwellSec: 20,
    estMinutes: 12,
    mdIds: ['md-store'],
    isOpen: true,
    color: '#0ea5a5',
  },
  {
    id: 'counter-ff',
    order: 4,
    slug: 'counter-ff',
    title: '카운터 FF 상품',
    subtitle: '즉석조리 · 카운터 푸드 신상품',
    type: 'shelf3d',
    modelPath: '/models/counter-ff.glb',
    hallPosition: { x: -19, z: 0, w: 11, d: 9 },
    requiredProductIds: ['pc-hotbar', 'pc-coffee', 'pc-bunsik'],
    minDwellSec: 20,
    estMinutes: 10,
    mdIds: ['md-ff'],
    isOpen: true,
    color: '#f97316',
  },
  {
    id: 'fresh',
    order: 5,
    slug: 'fresh',
    title: '신선강화점',
    subtitle: '신선식품 확대 운영 모델',
    type: 'shelf3d',
    modelPath: '/models/fresh.glb',
    hallPosition: { x: -6.5, z: 0, w: 11, d: 9 },
    requiredProductIds: ['pf-veg', 'pf-meal', 'pf-fruit'],
    minDwellSec: 20,
    estMinutes: 10,
    mdIds: ['md-fresh'],
    isOpen: true,
    color: '#22c55e',
  },
  {
    id: 'new-format',
    order: 6,
    slug: 'new-format',
    title: '뉴포맷 운영컨셉',
    subtitle: '상권별 특화 매장 컨셉',
    type: 'content',
    hallPosition: { x: 6.5, z: 0, w: 11, d: 9 },
    requiredProductIds: ['pn-office', 'pn-resi', 'pn-tour'],
    minDwellSec: 20,
    estMinutes: 8,
    mdIds: ['md-format'],
    isOpen: true,
    color: '#8b5cf6',
  },
  {
    id: 'education',
    order: 7,
    slug: 'education',
    title: '교육지원팀 교육내용',
    subtitle: '경영주 · 근무자 교육 프로그램',
    type: 'content',
    hallPosition: { x: 19, z: 0, w: 11, d: 9 },
    requiredProductIds: ['pe-onboard', 'pe-online', 'pe-safety'],
    minDwellSec: 20,
    estMinutes: 7,
    mdIds: ['md-edu'],
    isOpen: true,
    color: '#0891b2',
  },
  {
    id: 'ax-auto-order',
    order: 8,
    slug: 'ax-auto-order',
    title: 'AX부문 자동발주',
    subtitle: 'AI 발주 추천 · 재고 최적화',
    type: 'content',
    hallPosition: { x: -19, z: -13, w: 11, d: 9 },
    requiredProductIds: ['pa-auto', 'pa-forecast', 'pa-app'],
    minDwellSec: 20,
    estMinutes: 9,
    mdIds: ['md-ax'],
    isOpen: true,
    color: '#4f46e5',
  },
  {
    id: 'win-win',
    order: 9,
    slug: 'win-win',
    title: '상생협력팀 경영주 협의회',
    subtitle: '상생 제도 · 경영주 협의회 운영',
    type: 'content',
    hallPosition: { x: -6.5, z: -13, w: 11, d: 9 },
    requiredProductIds: ['pv-council', 'pv-support', 'pv-welfare'],
    minDwellSec: 20,
    estMinutes: 7,
    mdIds: ['md-winwin'],
    isOpen: true,
    color: '#e11d48',
  },
  {
    id: 'souvenir',
    order: 10,
    slug: 'souvenir',
    title: '기념품존',
    subtitle: '현장에서만 만날 수 있는 5가지',
    type: 'souvenir',
    hallPosition: { x: 6.5, z: -13, w: 11, d: 9 },
    requiredProductIds: ['pg-teaser'],
    minDwellSec: 15,
    estMinutes: 4,
    mdIds: ['md-hq'],
    isOpen: true,
    color: '#d946ef',
  },
  {
    id: 'exit',
    order: 11,
    slug: 'exit',
    title: '퇴점',
    subtitle: '완주 확인 · 설문 · 수료증',
    type: 'exit',
    hallPosition: { x: 19, z: -13, w: 11, d: 9 },
    requiredProductIds: [],
    minDwellSec: 10,
    estMinutes: 4,
    mdIds: ['md-hq'],
    isOpen: true,
    color: '#0f223e',
  },
];

export const SECTION_BY_SLUG = Object.fromEntries(SECTIONS.map((s) => [s.slug, s]));
export const SECTION_BY_ID = Object.fromEntries(SECTIONS.map((s) => [s.id, s]));

/** 조감도 동선: 입구 → 퇴점 순서의 중심 좌표 */
export const TOUR_PATH = SECTIONS.map((s) => ({
  id: s.id,
  x: s.hallPosition.x,
  z: s.hallPosition.z,
}));
